name: "Portfolio Readme Parser"
description: "Take an .md input and output a .md string with the desired elements"
inputs:
  title:
    description: "the title the file should have"
  path:
    description: "the input path"
    required: true
outputs:
  markdown:
    description: "the output string"
runs:
  using: "node20"
  main: "index.js"
