name: "Portfolio Readme Parser"
description: "Take an .md input and output a .md string with the desired elements"
inputs:
  title:
    description: "the title the file should have"
    required: true
  path:
    description: "the input path"
    required: true
  tags:
    description: "Tags that should be displayed on the page"
    tags: "github"
  thumbnail:
    description: "Thumbnail of the project"
    default: "images/code.png"
outputs:
  markdown:
    description: "the output string"
runs:
  using: "node20"
  main: "index.js"
